# Generated by Django 5.0 on 2025-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_category_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='request_photos/', verbose_name='Фото проблемы'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
